### ISSUE TITLE
Migrate to vanilla git

### ISSUE THREAD

**Issue by dz-paji** [saber-nyan/ddlc-android#13]
![image](https://user-images.githubusercontent.com/19299425/34822905-736e8078-f703-11e7-8582-27e24aaaf6b4.png)

It seems that this repository run out of chart?

**Comment by saber-nyan** [comment]
Yep, sorry...
![s80111-14394148](https://user-images.githubusercontent.com/25345196/34823910-60869b06-f6dd-11e7-8e4e-20fe5711436e.jpg)

Soon I'll transfer the repository to a vanilla git.

**Comment by saber-nyan** [comment]
Btw you can use [Lattyware/unrpa](https://github.com/Lattyware/unrpa) to extract `*.rpa` files and copy missing resources.

**Comment by dz-paji** [comment]
All right. Thanks :)

**Comment by saber-nyan** [comment]
Typo in commit message~
