### ISSUE TITLE
FYI: Already working(?) DDLC android fork

### ISSUE THREAD

**Issue by gitthisissue** [saber-nyan/ddlc-android#14]
https://www.reddit.com/r/DDLC/comments/7l91dr/doki_doki_litarature_club_android_port_fixed_3/

I didn't download it but it seems everyone like it.
Too bad he's hosting on MEGA and using advertisement to make money from it.

So, @saber-nyan - if you're really working on this Android unofficial port, you might can learn something from its apk file.

**Comment by gitthisissue** [comment]
And you might want to post this github's URL to https://www.reddit.com/r/DDLC/ , because I didn't notice
about this project until I searched on searx.me.

**Comment by saber-nyan** [comment]
Thanks, I already saw this fork and wanted to use parts of the code from there.
The main purpose of my fork is to port the Russian version of the game. Unfortunately, the already released translations are bad, so I'm waiting for the last team.

I do not have a Reddit account, and my target audience is Russian speakers, but you can create a thread and write about it here.

By the way, does the author know about the developer's attitude to porting DDLC to other platforms?

**Comment by gitthisissue** [comment]
@saber-nyan

I don't think the author(blogspot's) know about DDLC developer's attitude.
He's creating many forks. Without permission, I assume.

And I didn't test his APK because I don't like see-ads-to-download links.

Is your fork's language Russian only?
If you can fork English version and post it on Github/releases/ I would like to try it.

I don't have reddit account too, but I'll post about this soon to gather some help.

**Comment by saber-nyan** [comment]
> I don't think the author(blogspot's) know about DDLC developer's attitude.
> He's creating many forks. Without permission, I assume.

Hmm, if he makes money on this, I think you can complain to the moderator.
http://teamsalvato.com/ip-guidelines/ says:
```
You are NOT allowed to redistribute DDLC or fan games on any app store including Steam, the Google Play
Store, the Apple App Store, the Windows Store, or any others. You may not port DDLC or any fan game to
these platforms.
```

> Is your fork's language Russian only?

No, but at this moment fork is not fully functional.

> If you can fork English version and post it on Github/releases/ I would like to try it.

You can try the current version, it's in English. But do not do this if you haven't completed the game.


Btw, you do not have to mention me, I follow the entire repository.

**Comment by gitthisissue** [comment]
> if he makes money on this,

Under his blog, there's a "Mega" link. Click it, and you'll see Advertisements and 5 seconds timelock(to see actual mega link).

> But do not do this if you haven't completed the game.

I already completed the game on PC, if that's what you're asking.

Suggestion:
1. Include "You can download [APK here](https://github.com/saber-nyan/ddlc-android/releases)." to "Readme.md"
2. In /releases, it'll be nice if you can add English description.

Ok, I [posted to reddit](https://www.reddit.com/r/DDLC/comments/7q4o0g/doki_doki_literature_club_android_port/).

**Comment by saber-nyan** [comment]
Done!
