### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by gitthisissue** [saber-nyan/ddlc-android#15]
(how about adding a "Wiki" tab to this github for Q&A section?)

1. Does this fork support "Monika After Story" mod?
I'm using it on PC. https://github.com/Backdash/MonikaModDev

2. Why the filesize is so big, compared to blogspot's APK?
IIRC, that filesize is about 1xxMB. (one apk file)
Yours is 21.99MB(apk) + 215.04MB(obb). I wonder why.

3. If I want English only, I don't have to download .obb file or not?

**Comment by saber-nyan** [comment]
Answered all questions in FAQ~
