### ISSUE TITLE
Where is the Character menu

### ISSUE THREAD

**Issue by bobeable** [saber-nyan/ddlc-android#21]
I downloaded the game and started the newest release of the .apk for DDLC and when I read the information when downloading the game that there was a new character menu, but after looking for a long time I could not find it. Does anyone know where it is I need help.

**Comment by saber-nyan** [comment]
This button is hidden under `persistent.playthrough > 0`, see this:
 https://github.com/saber-nyan/ddlc-android/blob/bbc9d7f9153e281525f4711b00c8f1a8ca35ec75/game/screens.rpy#L464-L466
You should see the "Characters" button after the first reading of the visual novel, ~~after Sayori commits suicide~~.

It looks like this (some text on my machine is broken, dunno why):
![screenshot0001](https://user-images.githubusercontent.com/25345196/37352614-b7cb1f9a-26ee-11e8-807c-ec4da1b1298b.png)

**Comment by bobeable** [comment]
Thank you so much this really helped :)
