### ISSUE TITLE
Инструкция по установке

### ISSUE THREAD

**Issue by parklir** [saber-nyan/ddlc-android#7]
Напиши полную инструкцию по установке хотя бы этой версии, а то чёт не получается

**Comment by saber-nyan** [comment]
А как ты пытался установить?
Там надо:
1. Скачать `.apk` и `.obb` файл [отсюда](https://github.com/saber-nyan/ddlc-android/releases)
2. Установить `apk`, но не запускать его
3. Создать директорию `/sdcard/Android/obb/ru.saber_nyan.ddlc/`
4. Поместить туда скачанный `obb`

Так-то обычная процедура установки игр с кэшем на Android.
Но если нужно, могу собрать один большой `apk`.

**Comment by parklir** [comment]
@saber-nyan Спасибо, щас попробую, получится или нет отпишусь

**Comment by parklir** [comment]
@saber-nyan установка норм, а где перевод? 😯
![screenshot_20171213-205348](https://user-images.githubusercontent.com/34506448/33954107-646eb358-e048-11e7-9408-e38781c64b65.png)
![screenshot_20171213-205426](https://user-images.githubusercontent.com/34506448/33954121-6c32430c-e048-11e7-981e-731bc2ec9fc3.png)
![screenshot_20171213-205502](https://user-images.githubusercontent.com/34506448/33954217-a6339a38-e048-11e7-91a9-ecc52500de10.png)

**Comment by parklir** [comment]
@saber-nyan или его и не было
Upd. Просто когда я по ссылке переходил там было написано что язык в игре русский

**Comment by saber-nyan** [comment]
Не было, сейчас [вот здесь](http://vk.com/doki_doki_literature_club) делается.
Но там простой английский.

**Comment by saber-nyan** [comment]
@parklir 
> когда я по ссылке переходил там было написано что язык в игре русский

Ты про vndb? Там TBA написано, вроде.
