### ISSUE TITLE
Can't open image files.

### ISSUE THREAD

**Issue by dz-paji** [saber-nyan/ddlc-android#9]
I'm running windows 10 with creator update. After I download this project in Zip and tried to open the image files which located in ./game/GUI and ./game/img , Windows photos told me it can't load it.
![image](https://user-images.githubusercontent.com/19299425/34607741-eb5bee80-f24f-11e7-8d87-423299d81e99.png)
And to make sure this is not the fault of Unzip program, i tried both WinZip and WinRAR.
So what makes this issue and how can I fix it?

**Comment by saber-nyan** [comment]
Please try to open images with another image viewer. For example, [IrFan](http://www.irfanview.com).

**Comment by dz-paji** [comment]
![image](https://user-images.githubusercontent.com/19299425/34608813-152ec804-f255-11e7-9d3b-8d11b53d5edc.png)
it seems didn't make sense...

**Comment by dz-paji** [comment]
well, solved by clone useing git. Maybe download zip is not a good idea for me.
Thanks for help

**Comment by saber-nyan** [comment]
Oh, it's because of git-lfs.
